image: ruby

cache:
  paths:
  - vendor

test:
  script:
  - gem install bundler:1.15.3
  - apt-get update -y
  - apt-get install -y nodejs npm
  - npm install -g bower
  - bundle install --path vendor
  - bower --allow-root install
  - bundle exec middleman build
  - du -hs build
  except:
    - master

pages:
  script:
  - gem install bundler:1.15.3
  - apt-get update -y
  - apt-get install -y nodejs npm
  - npm install -g bower
  - bundle install --path vendor
  - bower --allow-root install
  - bundle exec middleman build
  - du -hs build
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master
