image: ruby

cache:
  paths:
  - vendor

test:
  script:
  - apt-get update -y
  - apt-get install -y nodejs npm
  - npm install -g bower
  - bundle install --path vendor
  - bower --allow-root install
  - bundle exec middleman build
  - du -hs build
  except:
    - master

pages:
  script:
  - apt-get update -y
  - apt-get install -y nodejs npm
  - npm install -g bower
  - bundle install --path vendor
  - bower --allow-root install
  - bundle exec middleman build
  - du -hs build
  artifacts:
    paths:
    - build
  only:
  - master
