image: ruby

cache:
  paths:
  - vendor

test:
  script:
  - apk --update add nodejs npm
  - npm install -g bower
  - bundle install --path vendor
  - bower install
  - bundle exec middleman build
  except:
    - master

pages:
  script:
  - apk --update add nodejs npm
  - npm install -g bower
  - bundle install --path vendor
  - bower install
  - bundle exec middleman build
  artifacts:
    paths:
    - public
  only:
  - master
